
version: '2'

services:
  retail:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: mvn spring-boot:run -Dspring.profiles.active=dev,docker-mysql
    ports:
      - "9021:9021"
    depends_on:
      - db
    volumes:
      - .:/code
  db:
    image: percona
    ports:
      - "11021:3306"
    environment:
      MYSQL_DATABASE: 'sspms'
      MYSQL_ROOT_PASSWORD: 'tenxdev'
